# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignFileManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.MainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.CurrentPathsLabels = QtWidgets.QHBoxLayout()
        self.CurrentPathsLabels.setObjectName("CurrentPathsLabels")
        self.lblCurrentPathDynamic = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCurrentPathDynamic.setEnabled(True)
        font = QtGui.QFont()
        self.lblCurrentPathDynamic.setFont(font)
        self.lblCurrentPathDynamic.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrentPathDynamic.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lblCurrentPathDynamic.setObjectName("lblCurrentPathDynamic")
        self.CurrentPathsLabels.addWidget(self.lblCurrentPathDynamic)
        self.lblCurrentPathStatic = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCurrentPathStatic.setEnabled(True)
        font = QtGui.QFont()
        self.lblCurrentPathStatic.setFont(font)
        self.lblCurrentPathStatic.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrentPathStatic.setObjectName("lblCurrentPathStatic")
        self.CurrentPathsLabels.addWidget(self.lblCurrentPathStatic)
        self.MainLayout.addLayout(self.CurrentPathsLabels)
        self.LayoutPanels = QtWidgets.QHBoxLayout()
        self.LayoutPanels.setObjectName("LayoutPanels")
        self.panelDynamic = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.panelDynamic.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.panelDynamic.setPalette(palette)
        self.panelDynamic.setFrameShape(QtWidgets.QFrame.Box)
        self.panelDynamic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panelDynamic.setLineWidth(1)
        self.panelDynamic.setObjectName("panelDynamic")
        self.LayoutPanels.addWidget(self.panelDynamic)
        self.panelStatic = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.panelStatic.setFrameShape(QtWidgets.QFrame.Box)
        self.panelStatic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.panelStatic.setLineWidth(1)
        self.panelStatic.setMidLineWidth(0)
        self.panelStatic.setObjectName("panelStatic")
        self.LayoutPanels.addWidget(self.panelStatic)
        self.MainLayout.addLayout(self.LayoutPanels)
        self.BtnLayout = QtWidgets.QHBoxLayout()
        self.BtnLayout.setObjectName("BtnLayout")
        self.btnChangePanel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnChangePanel.setObjectName("btnChangePanel")
        self.BtnLayout.addWidget(self.btnChangePanel)
        self.MainLayout.addLayout(self.BtnLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblCurrentPathDynamic.setText(_translate("MainWindow", "TextLabel"))
        self.lblCurrentPathStatic.setText(_translate("MainWindow", "TextLabel"))
        self.btnChangePanel.setText(_translate("MainWindow", "Поменять панели"))
