# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogSaveSetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DialogSaveSetup(object):
    def setupUi(self, DialogSaveSetup):
        DialogSaveSetup.setObjectName("DialogSaveSetup")
        DialogSaveSetup.resize(242, 100)
        DialogSaveSetup.setSizeGripEnabled(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(DialogSaveSetup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameSaveSetup = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frameSaveSetup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameSaveSetup.setFrameShape(QtWidgets.QFrame.Box)
        self.frameSaveSetup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSaveSetup.setLineWidth(1)
        self.frameSaveSetup.setObjectName("frameSaveSetup")
        self.label = QtWidgets.QLabel(self.frameSaveSetup)
        self.label.setGeometry(QtCore.QRect(0, 10, 221, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frameSaveSetup)
        self.buttonBox.setGeometry(QtCore.QRect(30, 40, 156, 31))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.frameSaveSetup)

        self.retranslateUi(DialogSaveSetup)
        self.buttonBox.accepted.connect(DialogSaveSetup.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSaveSetup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSaveSetup)

    def retranslateUi(self, DialogSaveSetup):
        _translate = QtCore.QCoreApplication.translate
        DialogSaveSetup.setWindowTitle(_translate("DialogSaveSetup", "Сохранение"))
        self.label.setText(_translate("DialogSaveSetup", "<html><head/><body><p align=\"center\">Сохранить текущую конфигурацию?</p></body></html>"))
